# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('login', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
