# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-03 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170427_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
