# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-17 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170517_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='productinorder',
            old_name='nmd',
            new_name='nmb',
        ),
    ]
